Training pipeline

diff --git a/docker-compose-wo-airflow.yaml b/docker-compose-wo-airflow.yaml
--- a/docker-compose-wo-airflow.yaml
+++ b/docker-compose-wo-airflow.yaml
@@ -1,3 +1,33 @@
+x-airflow-common:
+  &airflow-common
+  image: my-airflow-image
+  user: "${AIRFLOW_UID:-50000}"
+  group_add:
+    - "990" 
+  environment:
+    &airflow-common-env
+    AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
+    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres_db:5432/airflow"
+    AIRFLOW__CORE__FERNET_KEY: "A0C4Hjk1ToTD3_BkfQFSijHqH4pKXuw5UUM4yDuE1i0="
+    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
+    AIRFLOW__CORE__DEFAULT_TIMEZONE: "Asia/Bangkok"
+    AIRFLOW_CONN_SPARK_DEFAULT: "spark://spark-master:7077"
+    AIRFLOW_CONN_DOCKER_DEFAULT: "docker://local/var/run/docker.sock"
+    PYSPARK_DRIVER_PYTHON: "/usr/local/bin/python3"
+    PYSPARK_PYTHON: "/usr/local/bin/python3"
+  volumes:
+    - ./airflow/dags:/opt/airflow/dags:rw
+    - ./airflow/logs:/opt/airflow/logs:rw
+    - ./airflow/plugins:/opt/airflow/plugins:rw
+    - ./spark/apps:/opt/spark_apps:ro
+    - /var/run/docker.sock:/var/run/docker.sock
+  networks:
+    - nebula-net 
+  depends_on:
+    postgres_db:
+      condition: service_healthy 
+
 services:
   cassandra:
     image: cassandra:3.11
@@ -291,6 +321,7 @@ services:
     cap_add:
       - SYS_PTRACE
 
+
   graphd:
     image: docker.io/vesoft/nebula-graphd:v3.8.0
     environment:
@@ -530,9 +561,9 @@ services:
     user: "1001:1001"
     environment:
       - SPARK_MODE=master
-      - SPARK_OPTS=--conf spark.driver.memory=20g --conf spark.driver.cores=12 --conf spark.hadoop.fs.defaultFS=hdfs://namenode:8020
+      - SPARK_OPTS=--conf spark.driver.memory=14g --conf spark.driver.cores=4 --conf spark.hadoop.fs.defaultFS=hdfs://namenode:8020
       - PYSPARK_PYTHON=/usr/local/bin/python3
-    mem_limit: 22g
+    mem_limit: 16g
     ports:
       - "8080:8080"
       - "7077:7077"
@@ -554,7 +585,7 @@ services:
       - SPARK_MODE=worker
       - SPARK_MASTER_URL=spark://spark-master:7077
       - SPARK_OPTS=--conf spark.hadoop.fs.defaultFS=hdfs://namenode:8020
-      - SPARK_WORKER_MEMORY=12g
+      - SPARK_WORKER_MEMORY=14g
       - SPARK_WORKER_CORES=4
       - PYSPARK_PYTHON=/usr/local/bin/python3
     depends_on:
@@ -567,6 +598,93 @@ services:
     networks:
       - nebula-net
 
+  postgres_db:
+    image: postgres:13
+    container_name: airflow_postgres_db
+    environment:
+      - POSTGRES_USER=airflow
+      - POSTGRES_PASSWORD=airflow
+      - POSTGRES_DB=airflow
+    volumes:
+      - airflow_postgres_meta_data:/var/lib/postgresql/data
+    networks:
+      - nebula-net
+    healthcheck:
+      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
+      interval: 10s
+      timeout: 5s
+      retries: 5
+
+  airflow-init:
+    <<: *airflow-common
+    container_name: airflow_init
+    command:
+      - bash
+      - -c
+      - |
+        # This script is idempotent, meaning it can be run multiple times safely.
+        
+        # 1. Initialize or upgrade the Airflow database
+        echo "Initializing or upgrading the Airflow database..."
+        airflow db upgrade
+        
+        # 2. Check if the 'admin' user already exists
+        echo "Checking for admin user..."
+        if ! airflow users list | grep -q "admin"; then
+          # Create the admin user only if it does not exist
+          echo "Admin user not found. Creating admin user..."
+          airflow users create \
+            --username admin \
+            --firstname Admin \
+            --lastname User \
+            --role Admin \
+            --email admin@example.com \
+            --password admin
+        else
+          echo "Admin user already exists. Skipping creation."
+        fi
+        
+        # 3. Add or update the Spark connection (this command is idempotent by default)
+        # echo "Adding/updating connection..."
+        # airflow connections add 'spark-spark' --conn-type 'spark' --conn-host 'spark://spark-master' --conn-port '7077' --conn-extra '{"master": "spark://spark-master:7077"}';
+    user: "0:0"
+    depends_on:
+      postgres_db:
+        condition: service_healthy
+
+  airflow-webserver:
+    <<: *airflow-common
+    container_name: airflow_webserver
+    command: webserver
+    ports:
+      - "8081:8080" 
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
+      interval: 30s
+      timeout: 10s
+      retries: 5
+      start_period: 90s 
+    depends_on:
+      airflow-init:
+        condition: service_completed_successfully
+
+  airflow-scheduler:
+    <<: *airflow-common
+    container_name: airflow_scheduler
+    command: scheduler
+    healthcheck:
+      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname $$(hostname)"]
+      interval: 30s
+      timeout: 10s
+      retries: 5
+    depends_on:
+      airflow-init:
+        condition: service_completed_successfully
+        
 networks:
   nebula-net:
     driver: bridge
+
+volumes:
+  airflow_postgres_meta_data:
+    driver: local
